import Head from 'next/head'
import LoginPage from '../components/screen/Login/LoginPage'


export default function Home() {
  

  return (

    <>
      <Head>
        <title>Text Style</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <LoginPage/>
    </>
  )
}
