import Head from 'next/head'
// import { useEffect } from 'react'
// import api from '../services/api'
import { useForm } from 'react-hook-form'


export default function Home() {

  const { register, handleSubmit } = useForm()

  function handleSignIn(data) {
    console.log(data)
  }
  return (

    <>
      <Head>
        <title>Text Style</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <form className="mt-8 space-y-6" onSubmit={handleSubmit(handleSignIn)}>
        <input type="hidden" name="remember" defaultValue="true" />
        <div className="rounded-md shadow-sm -space-y-px">
          <div>
            <label htmlFor="email-address" className="sr-only">
              Email address
            </label>
            <input
              {...register("username")}
              id="username-address"
              name="username"
              type="username"
              autoComplete="username"
              required
              
              placeholder="Username address"
            />
          </div>
          <div>
            <label htmlFor="password" className="sr-only">
              Password
            </label>
            <input
              {...register("password")}
              id="password"
              name="password"
              type="password"
              autoComplete="current-password"
              required
             
              placeholder="Password"
            />
          </div>
        </div>

        <div >
          <div >
            <input
              id="remember_me"
              name="remember_me"
              type="checkbox"
              
            />
            <label
              htmlFor="remember_me"
              
            >
              Remember me
            </label>
          </div>

          <div >
            <a
              href="#"
              
            >
              Forgot your password?
            </a>
          </div>
        </div>

        <div>
          <button
            type="submit"
            
          >
            <span >
              
            </span>
            Sign in
          </button>
        </div>
      </form>
    </>
  )
}
